#!/usr/bin/env bash

# .local paths
if [ -d "$HOME/.local/bin" ]; then
	PATH+=":$HOME/.local/bin"
fi

# Doom Emacs
if [ -f "$HOME/.emacs.d/bin/doom" ]; then
	PATH+=":$HOME/.emacs.d/bin"
fi

# XDG Home
if [ -z "$XDG_CONFIG_HOME" ]; then
	export XDG_CONFIG_HOME="$HOME/.config"
fi

# XDG Run Dir
if [ -z "$XDG_RUNTIME_DIR" ]; then
	mkdir -p "/tmp/run-$EUID"
	chmod 700 "/tmp/run-$EUID"
	export XDG_RUNTIME_DIR="/tmp/run-$EUID"
fi

# Make vim the default editor.
export EDITOR='vim -u ~/.config/vim/vimrc.vim ';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
#export PYTHONIOENCODING='UTF-8';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
#export GPG_TTY=$(tty);

